### ISSUE TITLE
Perception Test Challenge 2025 Questions

### ISSUE THREAD

**Issue by ZhongZhi-Qiang** [deepmind/perception_test#31]
I'm a participant in the Perception Test Challenge 2025 - Task 2: Joint Object & Point Tracking. After submitting my results, I received the following evaluation error:

"ValueError: Missing video IDs in results, expected 44 videos, got 1031 videos."

I have a question regarding this error. As I understand it, the test set includes both object tracking and point tracking tasks. Shouldn't the total number of test videos correspond to the sum of both tasks (even if some videos are shared between them)? Why does the evaluation expect exactly 44 videos? Could there be an issue with the online evaluation system?

I'd appreciate any clarification on this. Thank you!

Let me know if you'd like it to sound more formal or technical.

<img width="1431" height="507" alt="Image" src="https://github.com/user-attachments/assets/c2d6b07a-7a1f-4350-befd-6a2deca6fa75" />

**Comment by viorik** [comment]
We have updated the challenge submission instructions https://eval.ai/web/challenges/challenge-page/2563/submission to clarify that when a video is missing object queries or point queries, that key should not be included at all for that video in the submission.
This should fix the error you are seeing. Let us know if that's not the case.

**Comment by ZhongZhi-Qiang** [comment]
> We have updated the challenge submission instructions https://eval.ai/web/challenges/challenge-page/2563/submission to clarify that when a video is missing object queries or point queries, that key should not be included at all for that video in the submission.我们更新了挑战提交说明 https://eval.ai/web/challenges/challenge-page/2563/submission ，以明确当视频缺少对象查询或点查询时，该视频提交的内容中根本不应包含该键。 This should fix the error you are seeing. Let us know if that's not the case.这应该可以修复您看到的错误。如果没有解决，请告知我们。

Dear organizers,

I encountered an error when submitting my result JSON file: "ValueError: number of points (2) does not match number of frame IDs (1051)." I've carefully checked the format of the uploaded JSON file and verified that the number of points corresponds to the number of frames, but the issue persists.

Attached is a sample of the JSON file I submitted. Could you please help me identify what might be causing this problem? Has anyone else successfully submitted under similar conditions?

Thank you for your support.

[debug.json](https://github.com/user-attachments/files/22488325/debug.json)

**Comment by viorik** [comment]
Clarified the format of points by email.
